language: ruby
rvm:
- 2.1

install: bundle install
before_script:
- openssl aes-256-cbc -K $encrypted_99b4d11c80c8_key -iv $encrypted_99b4d11c80c8_iv -in .travisdeploykey.enc -out .travisdeploykey -d
- chmod go-rwx .travisdeploykey
- eval `ssh-agent -s`
- ssh-add .travisdeploykey
- git config user.name "Travis-CI"
- git config user.email "noreply@travis-ci.org"
- COMMIT_MESSAGE="Publishing site on `date "+%Y-%m-%d %H:%M:%S"` from `git log -n 1 --format='commit %h - %s'`"
script:
- rake rebuild # rake cibuild
- set -e
- rake build
- git checkout -b gh-pages
- echo "outofdeadlock.io" > _site/CNAME
- git add -f _site/
- 'git commit -m "${COMMIT_MESSAGE}"'
- git stash
- git filter-branch -f --subdirectory-filter _site/
- git push -f git@github.com:tbrushwyler/outofdeadlock.git gh-pages:gh-pages

branches:
  only:
    - master

env:
- NOKOGIRI_USE_SYSTEM_LIBRARIES=true
